language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
sudo: required
addons:
  chrome: stable
notifications:
  email:
    on_success: never
    on_failure: always
script: npm run lint
deploy:
  - provider: script
    script: export URL=(npx now --token $NOW_TOKEN)
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: URL=https://trevordmiller.com npx now --token $NOW_TOKEN && npx now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
after_deploy: npm run verify
