language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
sudo: required
addons:
  chrome: stable
notifications:
  email:
    on_success: never
    on_failure: always
script: npm run verify
deploy:
  - provider: script
    script:
      - ./scripts/deploy-pull-request
      - ./scripts/after-deploy
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script:
      - ./scripts/deploy-master
      - ./scripts/after-deploy
    skip_cleanup: true
    on:
      master: true
